---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: emeraldsquad/concourse

inputs:
  - name: git-repo

outputs:
  - name: blobs

run:
  path: git-repo/ci/scripts/download-blobs