---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: emeraldsquad/concourse

inputs:
  - name: git-repo

outputs:
  - name: blobs

params:
  CONFIG_FILE: git-repo/ci-local/blobs.yml
  BLOBS_ROOT: blobs

run:
  path: git-repo/ci-local/scripts/download-blobs