---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: emeraldsquad/concourse
 
inputs:
  - name: git-repo
  - name: blobs

outputs:
  - name: blobstore

run:
  path: git-repo/ci/scripts/init-blobstore