---
meta:
  name:    haproxy
  target:  sw
  url:     https://ci.starkandwayne.com

  bosh-lite:
    target: https://10.58.111.49:25555
    username: (( vault "secret/bosh-lites/lite49/users/admin:username" ))
    password: (( vault "secret/bosh-lites/lite49/users/admin:password" ))
    cacert:   (( vault "secret/bosh-lites/lite49/certs:rootCA.pem" ))

  manifest:
    vars: |-
      haproxy-backend-port=8888
      haproxy-backend-servers=[10.10.10.10]

  aws:
    bucket: cf-haproxy-boshrelease-pipeline # re-use old ci bucket after boshrelease rename
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  cloudfoundry-incubator
    repo:   haproxy-boshrelease
    branch: master
    private_key:  (( vault "secret/pipelines/haproxy-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/haproxy-boshrelease/github:token" ))

  slack:
    webhook: (( vault "secret/pipelines/haproxy-boshrelease/slack:webhook" ))
    channel: '#haproxy-boshrelease'
    username:      starkandwayne-ci
    icon:          https://cl.ly/0o401h3l1x3R/logo-50x50.png
    blob_success:  '(( concat "$BUILD_PIPELINE_NAME: New version of $BUILD_JOB_NAME was detected, and updated in master. <" meta.url "/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME| Cut a new release?>" ))'
    blob_failure:  '(( concat "$BUILD_PIPELINE_NAME: :airplane_arriving: <" meta.url "/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME| Failed to update the blob for $BUILD_JOB_NAME>" ))'
